// TODO : 
"li x28, 0\n\t"
"li x29, 16\n\t"
"addi %[lw_cnt], %[lw_cnt], 2\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"Loop:\n\t"
"lh x5, (%[h])\n\t"
"addi %[h], %[h], 2\n\t"
"lh x6, (%[x])\n\t"
"addi %[x], %[x], 2\n\t"
"add x7, x5, x6\n\t"
"sh x7, (%[y])\n\t"
"addi %[y], %[y], 2\n\t"
"addi x28, x28, 1\n\t"
"addi %[arith_cnt], %[arith_cnt], 5\n\t"
"addi %[lw_cnt], %[lw_cnt], 2\n\t"
"addi %[sw_cnt], %[sw_cnt], 1\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"bne x28, x29, Loop\n\t"
"beq x28, x28, Exit\n\t"
"Exit:"

